packages:
    - "stack"
    - "stack/create"
allowBuilds:
    unrs-resolver: false
minimumReleaseAgeExclude:
    - termost
    - eslint-plugin-unicorn@66.0.0
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
