packages:
    - "stack"
    - "stack/create"
minimumReleaseAgeExclude:
    - "@adbayb/*"
    - termost
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*oxfmt*"
    - "*oxlint*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
saveExact: true
verifyDepsBeforeRun: "warn"
