packages:
    - "stack"
    - "stack/create"
allowBuilds:
    unrs-resolver: false
minimumReleaseAgeExclude:
    - "@vitest/eslint-plugin@1.6.18"
    - termost
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
