import { JAVASCRIPT_LIKE_FILES } from "../constants.js";

export const config = [
	{
		files: JAVASCRIPT_LIKE_FILES,
		rules: {
			"constructor-super": "error",
			"eqeqeq": "error",
			"for-direction": "error",
			"getter-return": "error",
			"no-alert": "error",
			"no-async-promise-executor": "error",
			"no-case-declarations": "error",
			"no-class-assign": "error",
			"no-compare-neg-zero": "error",
			"no-cond-assign": "error",
			"no-const-assign": "error",
			"no-constant-binary-expression": "error",
			"no-constant-condition": "error",
			"no-control-regex": "error",
			"no-debugger": "error",
			"no-delete-var": "error",
			"no-dupe-args": "error",
			"no-dupe-else-if": "error",
			"no-dupe-keys": "error",
			"no-duplicate-case": "error",
			"no-empty": "error",
			"no-empty-character-class": "error",
			"no-empty-pattern": "error",
			"no-empty-static-block": "error",
			"no-ex-assign": "error",
			"no-extra-boolean-cast": "error",
			"no-fallthrough": "error",
			"no-func-assign": "error",
			"no-global-assign": "error",
			"no-import-assign": "error",
			"no-invalid-regexp": "error",
			"no-irregular-whitespace": "error",
			"no-loss-of-precision": "error",
			"no-misleading-character-class": "error",
			"no-new-native-nonconstructor": "error",
			"no-nonoctal-decimal-escape": "error",
			"no-obj-calls": "error",
			"no-octal": "error",
			"no-prototype-builtins": "error",
			"no-redeclare": "error",
			"no-regex-spaces": "error",
			"no-restricted-syntax": [
				"error",
				{
					message: "Use undefined instead of null",
					// https://medium.com/@hbarcelos/why-i-banned-null-from-my-js-code-and-why-you-should-too-13df90323cfa
					selector: "Literal[raw='null']",
				},
			],
			"no-self-assign": "error",
			"no-setter-return": "error",
			"no-shadow-restricted-names": "error",
			"no-sparse-arrays": "error",
			"no-this-before-super": "error",
			"no-undef": "error",
			"no-unexpected-multiline": "error",
			"no-unreachable": "error",
			"no-unsafe-finally": "error",
			"no-unsafe-negation": "error",
			"no-unsafe-optional-chaining": "error",
			"no-unused-labels": "error",
			"no-unused-private-class-members": "error",
			"no-useless-backreference": "error",
			"no-useless-catch": "error",
			"no-useless-escape": "error",
			"no-var": "error",
			"no-with": "error",
			"object-shorthand": ["error", "always"],
			"padding-line-between-statements": [
				"error",
				{
					blankLine: "always",
					next: "*",
					prev: "*",
				},
				{
					blankLine: "never",
					next: ["const", "let", "var"],
					prev: ["const", "let", "var"],
				},
				{
					blankLine: "never",
					next: ["case", "default"],
					prev: ["case", "default"],
				},
				{
					blankLine: "always",
					next: ["const", "let", "var"],
					prev: ["multiline-const", "multiline-let", "multiline-var"],
				},
				{
					blankLine: "always",
					next: ["multiline-const", "multiline-let", "multiline-var"],
					prev: ["const", "let", "var"],
				},
				{
					blankLine: "any",
					next: ["expression"],
					prev: ["expression"],
				},
				{
					blankLine: "any",
					next: ["const", "let", "var"],
					prev: ["cjs-import"],
				},
				{
					blankLine: "any",
					next: ["cjs-import", "import"],
					prev: ["cjs-import", "import"],
				},
				{
					blankLine: "any",
					next: ["cjs-export", "export"],
					prev: ["cjs-export", "export"],
				},
			],
			"prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
			"prefer-const": "error",
			"prefer-rest-params": "error",
			"prefer-spread": "error",
			"prefer-template": "error",
			"require-yield": "error",
			"sort-imports": ["error", { ignoreDeclarationSort: true }],
			"sort-vars": "error",
			"use-isnan": "error",
			"valid-typeof": "error",
		},
	},
];
