import reactHooksPlugin from "eslint-plugin-react-hooks";
import reactPlugin from "@eslint-react/eslint-plugin";

import {
	JAVASCRIPT_LIKE_EXTENSIONS,
	TYPESCRIPT_EXTENSIONS,
} from "../constants.js";

export const config = [
	{
		files: JAVASCRIPT_LIKE_EXTENSIONS,
		plugins: {
			"react": reactPlugin,
			"react-hooks": reactHooksPlugin,
		},
		rules: {
			"react-hooks/exhaustive-deps": "warn",
			"react-hooks/rules-of-hooks": "error",
			"react/dom/no-dangerously-set-innerhtml": "error",
			"react/dom/no-dangerously-set-innerhtml-with-children": "error",
			"react/dom/no-find-dom-node": "error",
			"react/dom/no-flush-sync": "error",
			"react/dom/no-hydrate": "error",
			"react/dom/no-missing-button-type": "error",
			"react/dom/no-missing-iframe-sandbox": "error",
			"react/dom/no-namespace": "error",
			"react/dom/no-render": "error",
			"react/dom/no-script-url": "error",
			"react/dom/no-unsafe-iframe-sandbox": "error",
			"react/dom/no-unsafe-target-blank": "error",
			"react/dom/no-use-form-state": "error",
			"react/dom/no-void-elements-with-children": "error",
			"react/hooks-extra/no-direct-set-state-in-use-effect": "error",
			"react/hooks-extra/no-direct-set-state-in-use-layout-effect":
				"error",
			"react/hooks-extra/no-unnecessary-use-callback": "error",
			"react/hooks-extra/no-unnecessary-use-memo": "error",
			"react/hooks-extra/no-unnecessary-use-prefix": "error",
			"react/hooks-extra/prefer-use-state-lazy-initialization": "error",
			"react/jsx-key-before-spread": "error",
			"react/jsx-no-iife": "error",
			"react/naming-convention/component-name": "error",
			"react/naming-convention/context-name": "error",
			"react/naming-convention/use-state": "error",
			"react/no-access-state-in-setstate": "error",
			"react/no-children-prop": "error",
			"react/no-class-component": "error",
			"react/no-comment-textnodes": "error",
			"react/no-context-provider": "error",
			"react/no-create-ref": "error",
			"react/no-default-props": "error",
			"react/no-direct-mutation-state": "error",
			"react/no-duplicate-key": "error",
			"react/no-forward-ref": "error",
			"react/no-implicit-key": "error",
			"react/no-leaked-conditional-rendering": "error",
			"react/no-missing-component-display-name": "error",
			"react/no-missing-key": "error",
			"react/no-misused-capture-owner-stack": "error",
			"react/no-nested-component-definitions": "error",
			"react/no-nested-lazy-component-declarations": "error",
			"react/no-prop-types": "error",
			"react/no-string-refs": "error",
			"react/no-unstable-context-value": "error",
			"react/no-unstable-default-props": "error",
			"react/no-use-context": "error",
			"react/no-useless-fragment": "error",
			"react/prefer-shorthand-boolean": "error",
			"react/prefer-shorthand-fragment": "error",
			"react/web-api/no-leaked-event-listener": "error",
			"react/web-api/no-leaked-interval": "error",
			"react/web-api/no-leaked-resize-observer": "error",
			"react/web-api/no-leaked-timeout": "error",
		},
	},
	{
		files: TYPESCRIPT_EXTENSIONS,
		plugins: {
			react: reactPlugin,
		},
		rules: {
			"react/prefer-read-only-props": "error",
		},
	},
];
