import reactHooksPlugin from "eslint-plugin-react-hooks";
// eslint-disable-next-line depend/ban-dependencies
import reactPlugin from "eslint-plugin-react";

export const config = [
	{
		files: ["**/*.{jsx,tsx}"],
		plugins: {
			"react": reactPlugin,
			"react-hooks": reactHooksPlugin,
		},
		rules: {
			"react-hooks/exhaustive-deps": "warn",
			"react-hooks/rules-of-hooks": "error",
			"react/boolean-prop-naming": [
				"error",
				{ rule: "^(is|has)[A-Z]([A-Za-z0-9]?)+" },
			],
			"react/button-has-type": "error",
			"react/checked-requires-onchange-or-readonly": "error",
			"react/display-name": "error",
			"react/forbid-component-props": "error",
			"react/forward-ref-uses-ref": "error",
			"react/hook-use-state": "error",
			"react/iframe-missing-sandbox": "error",
			"react/jsx-boolean-value": "error",
			"react/jsx-fragments": "error",
			"react/jsx-handler-names": "error",
			"react/jsx-key": "error",
			"react/jsx-no-bind": "error",
			"react/jsx-no-constructed-context-values": "error",
			"react/jsx-no-leaked-render": "error",
			"react/jsx-no-script-url": "error",
			"react/jsx-no-target-blank": "error",
			"react/jsx-no-useless-fragment": "error",
			"react/jsx-pascal-case": "error",
			"react/jsx-props-no-spread-multi": "error",
			"react/jsx-sort-props": "error",
			"react/jsx-uses-react": "error",
			"react/jsx-uses-vars": "error",
			"react/no-access-state-in-setstate": "error",
			"react/no-array-index-key": "error",
			"react/no-arrow-function-lifecycle": "error",
			"react/no-children-prop": "error",
			"react/no-danger-with-children": "error",
			"react/no-did-mount-set-state": "error",
			"react/no-did-update-set-state": "error",
			"react/no-direct-mutation-state": "error",
			"react/no-find-dom-node": "error",
			"react/no-is-mounted": "error",
			"react/no-namespace": "error",
			"react/no-object-type-as-default-prop": "error",
			"react/no-redundant-should-component-update": "error",
			"react/no-render-return-value": "error",
			"react/no-string-refs": "error",
			"react/no-this-in-sfc": "error",
			"react/no-typos": "error",
			"react/no-unescaped-entities": "error",
			"react/no-unsafe": "error",
			"react/no-unstable-nested-components": "error",
			"react/no-unused-class-component-methods": "error",
			"react/no-unused-state": "error",
			"react/no-will-update-set-state": "error",
			"react/prefer-read-only-props": "error",
			"react/prefer-stateless-function": "error",
			"react/self-closing-comp": "error",
			"react/style-prop-object": "error",
			"react/void-dom-elements-no-children": "error",
		},
		settings: {
			react: {
				version: "detect",
			},
		},
	},
];
