minimumReleaseAgeExclude:
    - "@adbayb/*"
packages:
    - "examples/*"
    - "tools/*"
    - "{{projectName}}"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*oxfmt*"
    - "*oxlint*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
saveExact: true
verifyDepsBeforeRun: "warn"
