allowBuilds:
    esbuild: true
    unrs-resolver: true
minimumReleaseAgeExclude:
    - "@adbayb/*"
packages:
    - "examples/*"
    - "tools/*"
    - "{{projectName}}"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
saveExact: true
verifyDepsBeforeRun: "warn"
