minimumReleaseAgeExclude:
    - "@adbayb/*"
packages:
    - "applications/*"
    - "examples/*"
    - "libraries/*"
    - "tools/*"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
saveExact: true
verifyDepsBeforeRun: "warn"
