packages:
    - "applications/*"
    - "examples/*"
    - "libraries/*"
    - "tools/*"
allowBuilds:
    esbuild: true
saveExact: true
verifyDepsBeforeRun: "warn"
update:
    githubActions: true
minimumReleaseAgeExclude:
    - "@adbayb/*"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*oxfmt*"
    - "*oxlint*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
